# nonk8s
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xeksclusters.aws.infra.bigbang.dev
  labels:
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: infra.bigbang.dev/v1alpha1
    kind: XEKSCluster

  patchSets:
    - name: common-parameters
      patches:
        - fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.region"

  resources:
    - name: cluster-role
      base:
        apiVersion: iam.aws.crossplane.io/v1beta1
        kind: Role
        metadata:
          labels:
            internalName: cluster-role
        spec:
          forProvider:
            assumeRolePolicyDocument: |
              {
                "Version": "2012-10-17",
                "Statement": [
                  {
                    "Effect": "Allow",
                    "Principal": {
                    "Service": "eks.amazonaws.com"
                    },
                    "Action": "sts:AssumeRole"
                  }
                ]
              }
            description: "EKS Cluster IAM Role"
            tags:
              - key: Name
      patches:
        - fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.tags[0].value
          transforms:
            - type: string
              string:
                fmt: "%s-cluster"
    - name: rolepolicyattachment-cluster
      base:
        apiVersion: iam.aws.crossplane.io/v1beta1
        kind: RolePolicyAttachment
        metadata:
          labels:
            internalName: rolepolicyattachment-cluster
        spec:
          forProvider:
            policyArn: arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
            roleNameSelector:
              matchControllerRef: true
    - name: eks-cluster
      base:
        apiVersion: eks.aws.crossplane.io/v1beta1
        kind: Cluster
        metadata:
          labels:
            internalName: eks-cluster
        spec:
          forProvider:
            # encryptionConfig:                   # Not adding yet, but may want to in future
            logging:
              clusterLogging:
                - enabled: true
                  logTypes:
                    - api
                    - audit
                    - authenticator
                    - controllerManager
                    - scheduler
            resourcesVpcConfig:
              endpointPrivateAccess: true
              endpointPublicAccess: true
              # TODO: make this an optional variable
              publicAccessCidrs: ["0.0.0.0/0"]
              # Specify one or more security groups for the cross-account elastic network interfaces that Amazon EKS
              # creates to use to allow communication between your worker nodes and the Kubernetes control plane. If
              # you don't specify a security group, the default security group for your VPC is used.
              # securityGroupIds:              # Not adding yet, but may want to in future
            roleArnSelector:
              matchControllerRef: true
          writeConnectionSecretToRef:
            namespace: crossplane-system
      patches:
        - type: PatchSet
          patchSetName: common-parameters
        - fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.tags.name
        - fromFieldPath: spec.parameters.subnetMatchLabels
          toFieldPath: spec.forProvider.resourcesVpcConfig.subnetIdSelector.matchLabels
        - fromFieldPath: spec.parameters.k8sVersion
          toFieldPath: spec.forProvider.version
        - fromFieldPath: metadata.name
          toFieldPath: spec.writeConnectionSecretToRef.name
          transforms:
            - type: string
              string:
                fmt: "kubeconfig-%s"
      connectionDetails:
        - name: cluster-ca
          fromConnectionSecretKey: clusterCA
        - name: apiserver-endpoint
          fromConnectionSecretKey: endpoint
        - name: value
          fromConnectionSecretKey: kubeconfig
