# nonk8s
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xeksmanagednodegroups.infra.bigbang.dev
spec:
  group: infra.bigbang.dev
  names:
    kind: XEKSManagedNodeGroup
    plural: xeksmanagednodegroups
  claimNames:
    kind: EKSManagedNodeGroup
    plural: eksmanagednodegroups
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    region:
                      type: string
                      description: The region in which to create the EKS Cluster.
                    clusterNameMatchLabels:
                      description: The labels to match against the EKSCluster claim
                        to find the EKSCluster to use for this EKSManagedNodeGroup
                      type: object
                      additionalProperties: true
                    diskSize:
                      description: The root device disk size (in GiB) for each node in the nodegroup.
                      type: integer
                      minimum: 20
                    instanceTypes:
                      description: The instance type to use for your node group. Currently, you can specify a single instance type for a node group.
                      type: array
                      items:
                        type: string
                      minItems: 1
                      maxItems: 1
                    desiredNodeCount:
                      description: The desired number of worker nodes.
                      type: integer
                    minNodeCount:
                      description: The minimum number of worker nodes.
                      type: integer
                    maxNodeCount:
                      description: The maximum number of worker nodes.
                      type: integer
                    subnetMatchLabels:
                      description: The labels to match to when selecting subnets to deploy the cluster into
                      type: object
                      additionalProperties: true
                  required:
                    - region
                    - clusterNameMatchLabels
                    - diskSize
                    - instanceTypes
                    - desiredNodeCount
                    - minNodeCount
                    - maxNodeCount
                    - subnetMatchLabels
              required:
                - parameters
